services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_APP_API_URL=http://192.168.0.75:8010

  backend:
    stop_signal: SIGINT
    stdin_open: true
    build:
      context: ./backend
    command: >
      sh -c "poetry run python3 -m main"
    ports:
      - "8010:8010"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend