services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_APP_API_URL=http://192.168.0.75:8010

  backend:
    container_name: "backend"
    stop_signal: SIGINT
    stdin_open: true
    build:
      context: ./backend
    command: >
      sh -c "poetry run python3 -m main"
    ports:
      - "8010:8010"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  pyrobot:
    container_name: "pyrobot"
    build:
      context: pyrobot
      dockerfile: Dockerfile
    command: >
      sh -c "poetry run python3 -m main"
    restart: always
    links:
      - backend
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  aioyou:
    container_name: "aioyou"
    build:
      context: aiogram_youtube
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    command: >
      sh -c "poetry run python3 -m main"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  redis:
    container_name: "redis"
    image: redis:6.2-alpine
    ports:
      - "6388:6388"
    restart: always
    command: /bin/sh -c "redis-server --port $$REDISPORT --save 20 1 --loglevel warning --requirepass $$REDISPASSWORD"
    env_file:
      - .env