services:
  frontend:
    build:
      context: ./frontend # Путь к директории с вашим фронтенд-приложением
      dockerfile: Dockerfile # Имя Dockerfile
    ports:
      - "5173:5173" # Пробрасываем порт
    # depends_on:
    #   - backend # Указываем зависимость от бэкенда
    environment:
      - VITE_APP_API_URL=http://192.168.0.75:8010 # Пример переменной окружения для API

  backend:
    image: "fastapi"
    stop_signal: SIGINT
    stdin_open: true
    build:
      context: ./backend
    command: >
      sh -c "poetry run python3 -m main"
    ports:
      - "8010:8010"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"