# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bid.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbid.proto\x12\nBidPackage\"B\n\x0fMessageSendData\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\ttype_mess\x18\x03 \x01(\t\"2\n\x0fMessageFromPyro\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\ttype_mess\x18\x02 \x01(\t2^\n\x11MessageAddService\x12I\n\x0bSendMessage\x12\x1b.BidPackage.MessageSendData\x1a\x1b.BidPackage.MessageFromPyro\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGESENDDATA']._serialized_start=25
  _globals['_MESSAGESENDDATA']._serialized_end=91
  _globals['_MESSAGEFROMPYRO']._serialized_start=93
  _globals['_MESSAGEFROMPYRO']._serialized_end=143
  _globals['_MESSAGEADDSERVICE']._serialized_start=145
  _globals['_MESSAGEADDSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
