# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ws.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ws.proto\x12\tWsPackage\"C\n\x0fMessageSendPyro\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttype_mess\x18\x03 \x01(\t\"\x1f\n\x0fMessageFromBack\x12\x0c\n\x04text\x18\x01 \x01(\t2[\n\x10MessageWsService\x12G\n\x0bSendMessage\x12\x1a.WsPackage.MessageSendPyro\x1a\x1a.WsPackage.MessageFromBack\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGESENDPYRO']._serialized_start=23
  _globals['_MESSAGESENDPYRO']._serialized_end=90
  _globals['_MESSAGEFROMBACK']._serialized_start=92
  _globals['_MESSAGEFROMBACK']._serialized_end=123
  _globals['_MESSAGEWSSERVICE']._serialized_start=125
  _globals['_MESSAGEWSSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
