# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_utils.proto import bid_pb2 as bid__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BidServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createBulkEntries = channel.stream_stream(
                '/BidPackage.BidService/createBulkEntries',
                request_serializer=bid__pb2.EntryCreateRequest.SerializeToString,
                response_deserializer=bid__pb2.EntryResponse.FromString,
                _registered_method=True)


class BidServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createBulkEntries(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BidServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createBulkEntries': grpc.stream_stream_rpc_method_handler(
                    servicer.createBulkEntries,
                    request_deserializer=bid__pb2.EntryCreateRequest.FromString,
                    response_serializer=bid__pb2.EntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BidPackage.BidService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BidPackage.BidService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BidService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createBulkEntries(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/BidPackage.BidService/createBulkEntries',
            bid__pb2.EntryCreateRequest.SerializeToString,
            bid__pb2.EntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
