# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bid.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbid.proto\x12\nBidPackage\"5\n\x12\x45ntryCreateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\ttype_mess\x18\x02 \x01(\t\"0\n\rEntryResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\ttype_mess\x18\x02 \x01(\t2b\n\nBidService\x12T\n\x11\x63reateBulkEntries\x12\x1e.BidPackage.EntryCreateRequest\x1a\x19.BidPackage.EntryResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRYCREATEREQUEST']._serialized_start=25
  _globals['_ENTRYCREATEREQUEST']._serialized_end=78
  _globals['_ENTRYRESPONSE']._serialized_start=80
  _globals['_ENTRYRESPONSE']._serialized_end=128
  _globals['_BIDSERVICE']._serialized_start=130
  _globals['_BIDSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
