name: Deploy to Server
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker не установлен. Устанавливаем..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi
            cd /home/app
            git pull origin develop
            cd /ci-cd-test

            docker compose up -d --build
